### PR TITLE
Updated ControlNetDiff to use ControlNetVersioner.

### PR DESCRIPTION
**Pull request by kberryUSGS**
The unitTest fails, but I think this is due to toPvl still producing different output, and that can be addressed in a separate task. 

The test data needed to be updated to include `Version=3` because otherwise it gets treated as V1 and fails.

### CODE REVIEW

**Comment by kberryUSGS** [comment]
[Fix ControlNetDiff](https://trello.com/c/nARtLxP3/149-fix-controlnetdiff)

**Comment by kberryUSGS** [comment]
I added the separate task of updating and double-checking the unitTest after `toPvl` seems to be set here: https://trello.com/c/giU1PCrk

**Comment by kberryUSGS** [comment]
@jessemapel Yes, those are just for testing and I agree they should move to the test data area.

**Comment by jessemapel** [comment]
Since we have other networks that need to be moved maybe we should just wait and move all of them at once? Then we can merge this and move on. Then at the end do all of the moves at once.

**Comment by kberryUSGS** [comment]
@jessemapel I like that idea.

**Comment by kberryUSGS** [comment]
Card for it: https://trello.com/c/sEEDGUsC

**Pull request merged**
