### PR TITLE
Updated ControlPoint unit test to test new methods.

### PR DESCRIPTION
**Pull request by kberryUSGS**
I deliberately omitted testing the Apriori* methods since I think those are slated to be removed after Jeannie checks in her changes.

### CODE REVIEW

**Comment by kberryUSGS** [comment]
[Update ControlPoint unitTest](https://trello.com/c/l66h7687/142-update-controlpoint-unittest)

**Comment by jessemapel** [comment]
@kberryUSGS Can you pull Jeannie's changes in and remove those methods, because I don't think she did in her commit.

**Comment by kberryUSGS** [comment]
@jessemapel Sure!

**Comment by kberryUSGS** [comment]
@jessemapel Okay, done.

**Pull request merged**
